/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liux_ffmpeg_FFMpeg */

#ifndef _Included_com_liux_ffmpeg_FFMpeg
#define _Included_com_liux_ffmpeg_FFMpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liux_ffmpeg_FFMpeg
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liux_ffmpeg_FFMpeg_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
